# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPj9ITJ3ZE2StQWzt8iCY3fHEn6BZgG4
"""

import streamlit as st

# Title of the website
st.title("Text Group 6")

# Sidebar for navigation
st.sidebar.title("Navigation")
st.sidebar.radio("Go to", ["Home", "About", "Contact"])

# Home Section
if st.sidebar.radio("Go to", ["Home", "About", "Contact"]) == "Home":
    st.header("Welcome to Text Group 6!")
    st.write("This is a simple Streamlit application for Text Group 6.")
    st.write("Here, you can find various resources and information.")

    # Example of displaying an image
    st.image("path/to/your/image.jpg", caption="Group Image", use_column_width=True)

# About Section
elif st.sidebar.radio("Go to", ["Home", "About", "Contact"]) == "About":
    st.header("About Text Group 6")
    st.write("""
        Text Group 6 is a collaborative project that focuses on ...
        Here you can find our objectives, members, and more details.
    """)

# Contact Section
elif st.sidebar.radio("Go to", ["Home", "About", "Contact"]) == "Contact":
    st.header("Contact Us")
    st.write("If you have any questions, please reach out to us at:")
    st.text_input("Your Name")
    st.text_input("Your Email")
    st.text_area("Your Message")

# Footer
st.markdown("---")
st.write("© 2024 Text Group 6. All rights reserved.")